<?php

$title = 'Operation <DELETE> output:';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    <?php echo $this->escapeHtml($ubuntu->code_name); ?>
    <?php echo $this->escapeHtml($ubuntu->version); ?>?
</p>
<?php
$url = $this->url('crud', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $ubuntu->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>